
login_tub_locator = '[data-tab-target-id="loginSection"]'
login_locator = '#authenticationForm [name="username"]'
password_locator = '#authenticationForm [name="password"]'
submit = '#buttonSubmitLogin'
title_block_locator = '//a[text()="Головна"]'
collect_diamond_locator = '[data-btnname="Log In to Collect"]'
pop_up_locator = '.placement-top-center'
loader = '#spinner_share_specialOffer'
alert_block = '#SERVICE_CRASH_NOTIFY .warningBlock__title'
